### ISSUE TITLE
Scrum Updates 2 - June 10th

### ISSUE THREAD

**Issue by Huiwen-Zuo** [ddm1293/FurFinder#26]
Please leave the scrum summary under this issue.
What did you work on this past iteration (2 weeks)?
What were any major issues/challenges you ran into?
What do you plan to work on for this coming iteration (2 weeks)?

**Comment by cathylxy** [comment]
Xuanya Liu (CSID: t5n0b)
1. Past iteration: Implemented “Comment” and “Forum” components for the frontend that allow users to comment on and view threads. 
2. Challenges: Not have much experience on designing UI and implementing using React.  
3. Current iteration: Will be working on connecting backend and frontend for "Comment" feature, and more tasks to be assigned during our next meeting.

**Comment by ddm1293** [comment]
Yaosheng Cheng (j1a4n)

- What did you work on this past iteration (2 weeks)?

   - Set up the backend framework: Express, MongoDB, creating Mongoose models, and routes, and writing APIs stubs.
   - Implemented the basic CRUD APIs for the Thread models.
   - Implemented the CreadThread component groups, allowing users to create a thread and switch the type of thread.
   - Set up our JIRA and Swagger pages.

- What were any major issues/challenges you ran into?
  - Nothing particular
  
- What do you plan to work on for this coming iteration (2 weeks)?
   - I plan to mainly deal with the map-related BE work and start to design the pet matching algorithms (maybe pseudo-code first).
   - For the FE, I plan to work with our team to knit FE and BE together in the next sprint.

**Comment by Hann61** [comment]
Han Li (CSID: x2h3l)

Past iteration: Implemented “Navbar” component and Implemented the Comment model
Challenges: Not having much experience with Redux and API requests.  
Current iteration: Will be working on the connecting backend and frontend "Star a thread" feature, and more tasks to be assigned during our next meeting.

**Comment by Huiwen-Zuo** [comment]
Huiwen Zuo (n7l4u)

- What did you work on this past iteration (2 weeks)?
  - Implemented the Thread component and related styling. 
  - Attempted to complete the "login via Facebook" feature, but due to the Facebook censorship requirements, we abandoned this feature after discussion.

- What were any major issues/challenges you ran into?
  - Lack of experience, especially when it comes to Redux and databases.

- What do you plan to work on for this coming iteration (2 weeks)?
  - Would be mainly focused on connecting the backend and frontend for the Thread component to get the project ready for Progress 3.
  - After that, would be working on the GoogleMap API, or trying to deal with the "Login with Google" feature if we decided to do that.

**Comment by SeePeaJay** [comment]
Hank Chen (j4q1b)
What did you work on this past iteration (2 weeks)?
* home page
* merging my teammates' frontend work

What were any major issues/challenges you ran into?
* none that I can think of

What do you plan to work on for this coming iteration (2 weeks)?
* work on login component, both frontend and backend.
