### ISSUE TITLE
Scrum Updates 1 - May 27th

### ISSUE THREAD

**Issue by Huiwen-Zuo** [ddm1293/FurFinder#3]
Please leave the scrum summary under this issue.
What did you work on this past iteration (2 weeks)?
What were any major issues/challenges you ran into?
What do you plan to work on for this coming iteration (2 weeks)?

**Comment by Huiwen-Zuo** [comment]
Huiwen Zuo, CSID: N7L4U
1. Participating in all the prototyping discussions and helping to define the requirements for our project.
2. Nothing from the past iteration, but not familiar enough with the React making it challenging to start the upcoming coding work. Would finish Assignment 2 ASAP to get a better understanding of React.
3. Working with the team to fulfill all our minimum requirements, and if possible, start working on our forum-related standard requirements. Expecting to work with the whole team to finish the AssignmentProgress2-covered React design first, and then spend more time on the backend side.

**Comment by cathylxy** [comment]
Xuanya Liu (CSID: t5n0b)
1.  Past iteration: Participated in group discussions on project ideas, features, and requirements. 
2. Challenges: It will take me some time to learn React and apply to the project as I didn’t have previous experience working with React. 
3. Current iteration: Will be working on implementing backend of the minimum requirement “create/update/delete post” with the other group member and getting familiar with React to work on some of the components later.

**Comment by ddm1293** [comment]
Yaosheng Cheng (j1a4n)

- Proposed a project idea that was finalized and chosen as the group project. Participated in group discussions and finished project intro and project description. Created the project repository and our Jira page.
- Not really familiar with the design process of a software solution. Thought we could achieve more by drawing class diagrams, sequence diagrams, and maybe writing function stubs.
- Definitely will start coding and try to finish the forum part of our project (all minimum requirements and forum-related standard requirements) including the backend and frontend. Would like to learn docker & k8s and see if we are able to incorporate them.

**Comment by Hann61** [comment]
Han Li (CSID: x2h3l)
1) In the last iteration: participated in group meetings,brainstormed the project ideas and finished project progress 1 with group members. 
2) Not very familiar with the tech that we are gonna use in the future project.
3) Setting up our project with React, figuring out the components and working on the minimal requirements "create/update/delete thread" with group members.

**Comment by hc0000** [comment]
Hank Chen (CSID: j4q1b)
1. For the past iteration, my teammates and I essentially collaborated together to brainstorm what to create.
2. There was no major issue or challenges I ran into for the past 2 weeks.
3. As for the next iteration, we plan to break down the frontend of the website into React components we can work with, and decide which individual is responsible for which components (as of this writing I've been assigned to the "create/update/close a thread" minimal requirement).
