### ISSUE TITLE
Scrum Updates 3 - June 24th

### ISSUE THREAD

**Issue by Huiwen-Zuo** [ddm1293/FurFinder#40]
Please leave the scrum summary under this issue.
What did you work on this past iteration (2 weeks)?
What were any major issues/challenges you ran into?
What do you plan to work on for this coming iteration (2 weeks)?

**Comment by SeePeaJay** [comment]
Hank Chen (j4q1b)

What did you work on this past iteration?
* Both frontend and backend of login/signup feature

What were any major issues/challenges you ran into?
* Handling access token and refresh token is kind of tricky and I had to follow some tutorials to get the hang of it

What do you plan to work on for this coming iteration (2 weeks)?
* At the very least, fix ongoing bug issues, and handle image upload feature

**Comment by cathylxy** [comment]
Xuanya Liu (CSID: t5n0b)

Past iteration: Connected backend and frontend for "Comment" feature
Challenges: Understood other teammates' code
Current iteration: Will be working on debugging and adding validation for "Comment" feature, and more tasks to be assigned during our next meeting.

**Comment by Hann61** [comment]
Han Li (CSID: x2h3l)

Past iteration: Complete the BE comment API implementation; add unit test for comment API feature; work on the star feature;
Challenges: .env file doesn't work fix by reinstalling all the dependency
Current iteration: Will be working on debugging and adding validation for the "Comment" feature with Cathy; complete the  BE of the star feature and connect it with FE.

**Comment by Huiwen-Zuo** [comment]
Huiwen Zuo (n7l4u)

What did you work on this past iteration (2 weeks)
- Rewrote the Thread frontend, edited the backend and connected them. Made some changes to the Pet model and routers in the backend as well.

What were any major issues/challenges you ran into?
- Mapping the data while sending them to the BE, and dealing with the inconsistency between our BE and the database.

What do you plan to work on for this coming iteration (2 weeks)?
- Adding other features to our Thread feature (update for example); Rewrite the CSS perhaps; Other tasks would be assigned after our next meeting.

**Comment by ddm1293** [comment]
Yaosheng Cheng (j1a4n)
What did you work on this past iteration (2 weeks)?
I mainly focused on the search/filter functionality, both fronted and backend. Added unit testing framework as well.
What were any major issues/challenges you ran into?
procrastination
What do you plan to work on for this coming iteration (2 weeks)?
Work with the team to finish all our standard requirements, including the map functionality.

**Comment by kaiqianyyang** [comment]
> What did you work on this past iteration?
> 
> * Both frontend and backend of login/signup feature
> 
> What were any major issues/challenges you ran into?
> 
> * Handling access token and refresh token is kind of tricky and I had to follow some tutorials to get the hang of it
> 
> What do you plan to work on for this coming iteration (2 weeks)?
> 
> * At the very least, fix ongoing bug issues, and handle image upload feature

Name and CSID pls :)

**Comment by kaiqianyyang** [comment]
> What did you work on this past iteration (2 weeks)? I mainly focused on the search/filter functionality, both fronted and backend. Added unit testing framework as well. What were any major issues/challenges you ran into? procrastination What do you plan to work on for this coming iteration (2 weeks)? Work with the team to finish all our standard requirements, including the map functionality.

Name and CSID pls :)
