### ISSUE TITLE
Scrum Updates 4 - 15th July

### ISSUE THREAD

**Issue by Huiwen-Zuo** [ddm1293/FurFinder#57]
Please leave the scrum summary under this issue.
What did you work on this past iteration (2 weeks)?
What were any major issues/challenges you ran into?
What do you plan to work on for this coming iteration (2 weeks)?

**Comment by cathylxy** [comment]
Xuanya Liu (CSID: t5n0b)
1. Past iteration: worked on uploading user avatar and improved comment component.
2. Challenges: encountered many bugs when implementing uploading image.
3. Current iteration: Will be working on fix bugs and more tasks to be assigned during our next meeting.

**Comment by SeePeaJay** [comment]
Hank Chen (j4q1b)

What did you work on this past iteration?
* database seeding
* general UX improvements

What were any major issues/challenges you ran into?
* none that I can think of

What do you plan to work on for this coming iteration (2 weeks)?
* fix more UX-related bugs which should improve overall website usability
* work on breed selector

**Comment by Hann61** [comment]
Han Li (CSID: x2h3l)

Past iteration: working on both the backend and front end of favorite features.
Challenges: First time learning Axios.
Current iteration: Will be working on fixing bugs and more tasks to be assigned during our next meeting.

**Comment by Huiwen-Zuo** [comment]
Huiwen Zuo (n7l4u)

What did you work on this past iteration (2 weeks)?
 - The Thread Update feature, and related frontend and backend changes;
 - The Thread Map feature;
 - Refactoring the whole Thread page.

What were any major issues/challenges you ran into?
 - Nothing really, maybe first-time refactoring, have to deal with some issues.

What do you plan to work on for this coming iteration (2 weeks)?
 - The new Related Thread bar, mainly the frontend part;
 - Rewrite the CSS for the Thread page.

**Comment by ddm1293** [comment]
Yaosheng Cheng (j1a4n)

What did you work on this past iteration (2 weeks)?

Basically finished the map-related functionalities;

What were any major issues/challenges you ran into?

Nothing particularly

What do you plan to work on for this coming iteration (2 weeks)?

I will focus on the lost and witness threads linking algorithms and possibly help with the email notification functionalities.
