### ISSUE TITLE
Scrum Updates 5 - July 30th

### ISSUE THREAD

**Issue by Huiwen-Zuo** [ddm1293/FurFinder#69]
Please leave the scrum summary under this issue.
What did you work on this past iteration (2 weeks)?
What were any major issues/challenges you ran into?
What do you plan to work on for this coming iteration (2 weeks)?

**Comment by Hann61** [comment]
Han Li (x2h3l)
1) In the past iteration, I mainly focused on improving our project including separate "lost pets" and "witness" threads, adding a pop-up window for the condition of no matched search results, uploading pictures preview, uploading multiple pictures, etc.
2) Spend some time understanding other teammates' code.
3) Finish "Render my threads and my favorites on the profile page" and new tasks that I am assigned in the coming meetings.

**Comment by SeePeaJay** [comment]
Hank Chen j4q1b

What did you work on this past iteration (2 weeks)?
* update database script
* create thread route, breed selector
* misc. bug fixes

What were any major issues/challenges you ran into?
* n/a

What do you plan to work on for this coming iteration (2 weeks)?
* usability and more bug fixes

**Comment by cathylxy** [comment]
Xuanya Liu (CSID: t5n0b)
- Past iteration: worked on fixing bugs and implementing send notification feature
- Challenges: as the project gets larger, need to modify many places when implementing new feature. 
- Current iteration: Will be working on improvement on sending notification feature and fixing bugs.

**Comment by Huiwen-Zuo** [comment]
Huiwen Zuo (n7l4u)

What did you work on this past iteration (2 weeks)?
 -  The new Relevant Thread bar, mainly the frontend part;
 -  Rewrite the CSS for the Thread page;
 -  Bugs fix.

What were any major issues/challenges you ran into?
 - Nothing special, the CSS is quite annoying.

What do you plan to work on for this coming iteration (2 weeks)?
 - Update the Relevant Thread bar to be using Pet information, not small maps;
 - Update the Thread Pet Card component to be able to show multiple pictures;
 - General improvement work.

**Comment by ddm1293** [comment]
Yaosheng Cheng(j1a4n)
What did you work on this past iteration (2 weeks)?

- I am solely responsible for the witness-lost pet relevance algorithms
- I tried to create a cat face recognition ML model on Kaggle 

What were any major issues/challenges you ran into?

The ML model did not work well as I lack experience and knowledge. I could only apply existing and pre-trained models. Also, I did not have enough time for the ML;

For the algorithm, the main challenge is that we do not have enough reliable data to work with so most of the work is done based on assumptions.

What do you plan to work on for this coming iteration (2 weeks)?

I will keep working on the algorithm and related FE updates.
